### PR TITLE
update to work with patch 1.24.01

### PR DESCRIPTION
**Pull request by vitzeno**
Hello there, I've got a crude fix to make this work with the newest 1.24.01 patch. I've tested this with the EGS version of Nioh which was free this week.

### CODE REVIEW

**Comment by ScratchMode** [comment]
Well, whatever you did got the game resolution to work,  The UI is completely scuffed though, any idea what you missed?

**Comment by vitzeno** [comment]
> Well, whatever you did got the game resolution to work, The UI is completely scuffed though, any idea what you missed?

I messed about with the resolution stuff that I didn't fully understand yet, but I'll try have a look at it again later today.

**Comment by vitzeno** [comment]
> Thanks for the commit, any idea how to get it working for the Epic Games version? It's free on EGS now, would love to try the game out but no UW support is holding me back

I'm using the EGS version myself, just claimed it yesterday, so hopefully it should work for you too.

**Comment by dlQAQlb** [comment]
how could i fix it?(sorry i am a IT idiot) i am using 1920 1080 monitor

**Comment by p1xel8ted** [comment]
I have the Steam version, and this crashes the game to the desktop after the loading screen for me. 3440x1440. Looks like the update only introduced Epic cross-play stuff, so will go back a version until there is a fix.

**Comment by ScratchMode** [comment]
Well... hmmm. Running it after you reverted the ratios back to 1920x1080


```
Patching resolution to 3440x1440 with scale set to 1.0...
Width: 2580, Height: 1080
```
and the results were as expected, it sent me back to a square 16:9 standard resolution.

I ran it again at your previous ratios of 2560x1440 and it at least processed this part correctly
```

Patching resolution to 3440x1440 with scale set to 1.0...
Width: 3440, Height: 1440
```
But left the UI scuffed as before.

**Comment by ScratchMode** [comment]
Quick update,
After running the patch at the 1920X1080 original ratio, I was able to take some screenshots and confirm the game is rendering the screen at my desired 3440x1440.

It is however doing so with Pillar Boxes on either side.
This also appears to be atypical of the games default stretch to fit if launching vanilla 1920x1080
Nioh Screenshot 2021 09 10 - 20 37 03 11

**Comment by ScratchMode** [comment]
Ok... very positive update here. 
I ran a verify integrity on the game files to get a fresh Nioh.exe and then ran your latest revision of NiohResoluton with the 1920x1080 ratio.
I then ignored the closing message of
`- Set the Resolution to 1920x1080`
and went ahead and set the resolution to the max the launcher would allow. 4K.
Capture
Upon running the game now, it scales correctly to my 3440x1440 resolution. And the UI Hud looks identical to how i looked before the new epic games Nioh 1.24.01 patch.

A Complete success!
Nioh Screenshot 2021 09 10 - 21 55 51 16

Here's how it looks vanilla 4k running on my 3440x1440 resolution, notice how much wider the doorway is stretched to fit the ultrawide.
Nioh Screenshot 2021 09 10 - 21 50 07 94

**Comment by dlQAQlb** [comment]
how to i apply the update, do i have to wait for the poll or what?

**Comment by LennardF1989** [comment]
Sorry guys, mail didn't ping me for this. Will verify and update! Will test this with the ESG version.

**Comment by LennardF1989** [comment]
@ScratchMode Is that the result of the changes in this pull request?

**Comment by qlQAQlp** [comment]
oooo finally

**Comment by ScratchMode** [comment]
> @ScratchMode Is that the result of the changes in this pull request?

Yes, that was the result.
However the game is wildly unstable now. Crashed about 14 times in 3 hours of gameplay. 
I do not know if that's from NiohResolution or the developers update though, I didn't test without this fix.

And running it at 4k leaves things like the SteamOverlay all squished, game looks fine but all overlays are scaled at that 4k setting.

**Comment by Trokinos** [comment]
Thanks for this, i am no programmer and have no idea on how to use dependancies and making a VS build to make a new NiohResolution.exe , but i'm very happy i'll be able to lower the scale value once a new version of NiohResolution.exe is done to be able to play the game much more smoothly.

**Comment by PedrokaRJ** [comment]
I'm looking forward to the NiohResolution.exe update, my pc unfortunately doesn't run the game very well, and that makes me sad, thank god there are people like you

**Comment by LennardF1989** [comment]
@ScratchMode Just to make sure I understand the dialogue correctly: Did you grab @Vitzeno latest version, then set the ratioWidth/ratioHeight back to 1920x1080, and then patched the game with resolution set to 4k? Or did you leave the 2560x1440 that @Vitzeno set?

I practically re-patched the game from the ground up to update the offsets properly (the ones in this PR are not completely correct), but when I try to run your 3440x1440, I'm getting the pillar boxes you had too (you can see the circle in the UI is not completely round either).

So what exactly did you change between that screenshot and the second running at 4K (according to the launcher).

**Comment by ScratchMode** [comment]
> @ScratchMode Just to make sure I understand the dialogue correctly: Did you grab @Vitzeno latest version, then set the ratioWidth/ratioHeight back to 1920x1080, and then patched the game with resolution set to 4k? Or did you leave the 2560x1440 that @Vitzeno set?
> 
> I practically re-patched the game from the ground up to update the offsets properly (the ones in this PR are not completely correct), but when I try to run your 3440x1440, I'm getting the pillar boxes you had too (you can see the circle in the UI is not completely round either).
> 
> So what exactly did you change between that screenshot and the second running at 4K (according to the launcher).


Vitzeno himself switched the ratioWidth/ratioHeight back to 1920x1080, and that is what I have it set to now.
I patched the game to 3440x1440 with NiohResolution.exe.
Then in the Launcher chose the 4k option (3840x2160). That resulted in the successful run.

If I left it on 1920x1080 from the launcher I ended up with pillar boxes.

the Difference between the two screen shots at 4k are a vanilla version of the EXE without any NiohResolution, and a screenshot of a successfully applied NiohResolution.

I also overwrote all the original Steamless files from your Github project with the most recent steamless files form that github project.

**Comment by LennardF1989** [comment]
Got it, so what I think happened is that the developer tried to fix a few things themselves, as a result, some of the patches we used to apply are no longer relevant. It seems like when I try to run say a 1,6 aspect ration, 1,8 or 1,5, I actually have to select the 1920x1080. If you go to > 2 AR (which I cannot test myself), it looks like the game shouldn't try to mingle with the resolutions and ONLY patch the AR of the game.

I will create a preview release - if you would be so kind to test that out, I would be really grateful.

**Comment by ScratchMode** [comment]
Happy to help in any way I can. Appearing free on Epic seems to have revived the dead community so seems a worthwhile pursuit to get this working well.

Hopefully your improved offsets help with all the crashing as well.

**Comment by LennardF1989** [comment]
> Hopefully your improved offsets help with all the crashing as well.

Very most likely, this PR literally changes random bytes at places it shouldn't :P

**Comment by PedrokaRJ** [comment]
Will this new NiohResolution.exe patch be ready today? I'm really looking forward to playing......

**Comment by LennardF1989** [comment]
See https://github.com/LennardF1989/NiohResolution/pull/16#issuecomment-917480604

Please test this version and report your findings.

If you set 1920x1080 in the launcher, the game will try to use the resolution AND aspect ratio you set.
If you set anything else in the launcher, the game will use that resolution, but respect the aspect ratio you set. I reckon this works for you @ScratchMode because your monitor itself does something smart.

**Comment by PedrokaRJ** [comment]
> [NiohResolution.zip](https://github.com/LennardF1989/NiohResolution/files/7148496/NiohResolution.zip)
> Please test this version and report your findings.
> 
> If you set 1920x1080 in the launcher, the game will try to use the resolution AND aspect ratio you set.
> If you set anything else in the launcher, the game will use that resolution, but respect the aspect ratio you set. I reckon this works for you @ScratchMode because your monitor itself does something smart.

It is giving that the file has a virus '--'

**Comment by ScratchMode** [comment]
Leaving all the virus protection i had to disable, it kicked back this result
```

Unpacking nioh.exe...
-> Cannot process nioh.exe!

Unpacking of nioh.exe failed, this could mean the file is already unpacked and ready for patching.

Patching resolution to 3440x1440 with scale set to 1.0...
-> PATTERN_ASPECTRATIO1 expected 1, but got 0!

Patching failed, consider restoring a backup and try again.

Press any key to exit...
```

**Comment by LennardF1989** [comment]
Ah, you are on the Steam version... I assumed the EGS version, my bad, let me fix that up. Not sure where the virus notice comes from as it's released exactly the same way as the current (broken) version. I can assure you it's harmless and I will commit the code once verified.

**Comment by LennardF1989** [comment]
[NiohResolution-Steam+EGS.zip](https://github.com/LennardF1989/NiohResolution/files/7148521/NiohResolution-Steam%2BEGS.zip)
Here you go.

**Comment by raynan222** [comment]
Looks like the game is rendering on the right resolution, but still with black bars.
Tried both zip files _**NiohResolution.zip**_ and _**NiohResolution-Steam+EGS.zip**_.
2560x1080, EGS

**Comment by LennardF1989** [comment]
> 2560x1080, EGS

Just for fun and giggles, can you try setting the resolution to something close in the launcher? But not 1920x1080?

**Comment by ScratchMode** [comment]
EGS Nioh.exe says this
Unpacking nioh.exe...
```
-> Cannot process nioh.exe!

Unpacking of nioh.exe failed, this could mean the file is already unpacked and ready for patching.

Patching resolution to 3440x1440 with scale set to 1.0...
-> PATTERN_ASPECTRATIO1 expected 1, but got 0!

Patching failed, consider restoring a backup and try again.

Press any key to exit...
```

Steam I got these results on
If launched through the Nioh Launcher at 1920x1080, i still got the pillar boxes.
Nioh Screenshot 2021 09 11 - 15 12 31 93
If launched through the Nioh Launcher at 4K, It seems good again
Nioh Screenshot 2021 09 11 - 15 14 28 94

**Comment by LennardF1989** [comment]
@raynan222 
> 2560x1080, EGS

Just for fun and giggles, can you try setting the resolution to something close in the launcher? But not 1920x1080?

@ScratchMode 
Did you restore a clean backup of the exe before trying? I tested the Steam version just now and it should patch just fine.

**Comment by ScratchMode** [comment]
Here's the supposed virus report
Virus

**Comment by ScratchMode** [comment]
> @ScratchMode
> Did you restore a clean backup of the exe before trying? I tested the Steam version just now and it should patch just fine.

Sure did, and works on steam version for me now. See above for my results

**Comment by qlQAQlp** [comment]
It worked perfectly without crashing in 1280x 720 o.1 render resolution(lol ma pc sucks)

**Comment by LennardF1989** [comment]
@qlQAQlp Great to hear! Did you select 1920x1080 in the launcher or another resolution? And which version of the game are you testing (Steam or EGS), just for clarity :)

@ScratchMode So your resolution now also works on both versions, but only if you select the 4k resolution, and not the "patched" 1920x1080, correct?

**Comment by raynan222** [comment]
@LennardF1989 Looks like its only fixing if setted on higher resolution.
2040x1152
Got black bars on this one print, was not working.

2560x1440 WITH PATCH

2560x1440 WITHOUT PATCH


3840x2160 WITH PATCH
3840x2160

**Comment by LennardF1989** [comment]
@raynan222
> 2040x1152

I think I know why this is. This is like SLIGHTLY under 16/9 AR (1,7708 compared to 1,7777 to be exact), which means the game will try to compensate the 16/9 nature of the game (which it doesn't have to do for the other two you mentioned. as those are already 16/9). I wonder how a 16/10 behaves now...

**Comment by ScratchMode** [comment]
> @ScratchMode So your resolution now also works on both versions, but only if you select the 4k resolution, and not the "patched" 1920x1080, correct?

Correct, Tested on both , exact same results on both.

The "patched" 1920x1080 leads to Pillar Boxes.\

**Comment by LennardF1989** [comment]
@raynan222 I tried 204x1152 in Windowed mode and it shows perfectly fine to me.

image

Can you confirm this is also the case for you when running windowed/borderless?

**Comment by raynan222** [comment]
> @raynan222 I tried 204x1152 in Windowed mode and it shows perfectly fine to me.
> 
> Can you confirm this is also the case for you when running windowed/borderless?

not good on my end.
Windowed mode
windo

Boderless mode
boderless

**Comment by LennardF1989** [comment]
@raynan222 Can you try and set a resolution of 2040x1147 - I know it's a weird number, but it forces the game to be slightly above 16/9 - I'm curious if that removes the pillarboxes for you. Also, which GPU do you have and how does it handle scaling (eg. what happens if you run a 1024x768 game - will it maintain Aspect Ratio, or stretch to fill?)

**Comment by PedrokaRJ** [comment]
@LennardF1989 There would be how to remove the virus from the file.
NiohResolution, Pls, and the final version of the patch is out today???? Thanks for the file and the time!!!

**Comment by ScratchMode** [comment]
> @raynan222 Can you try and set a resolution of 2040x1147 - I know it's a weird number, but it forces the game to be slightly above 16/9 - I'm curious if that removes the pillarboxes for you. Also, which GPU do you have and how does it handle scaling (eg. what happens if you run a 1024x768 game - will it maintain Aspect Ratio, or stretch to fill?)

For the sake of science , I ran the patch on my EGS version of game at @raynan222 desired resolution of 2040x1152.
I launched at the required 1920x1080 from the launcher, and windowed mode. I got results without pillar boxes.
Nioh Screenshot 2021 09 11 - 17 44 46 67

I was curious if this meant launching my patched 3440x1440 game at 1920x1080 but in **windowed** would resolve the pillar boxes... but no same issue (not that i mind, since launching at 4k works for me)
Nioh Screenshot 2021 09 11 - 17 49 11 94

**Comment by tflori** [comment]
I can confirm running in 1920x1080 is still not working. Starting in a higher resolution (3840x2160) gets scaled down to my native resolution (3840x1600). However I have no idea why I'm able to select a higher resolution at first and how it selects the native resolution then nor if it renders then in 2160p (slower performance) or if it renders then also in the native resolution.

TBH: I would prefer the patch would work as expected. But thanks for your effort, at least it is now working in 21:9 in native resolution. 👍 ❤️

**Comment by ScratchMode** [comment]
> I can confirm running in 1920x1080 is still not working. Starting in a higher resolution (3840x2160) gets scaled down to my native resolution (3840x1600). However I have no idea why I'm able to select a higher resolution at first and how it selects the native resolution then nor if it renders then in 2160p (slower performance) or if it renders then also in the native resolution.
> 
> TBH: I would prefer the patch would work as expected. But thanks for your effort, at least it is now working in 21:9 in native resolution. 👍 ❤️

if you feel like the performance is tanking from some kind of down scaling you could try to adjust the scale to <1 setting while performing the NiohResolution patch. It will prompt you to do so whilst installing

Capture

**Comment by Azrafael** [comment]
Necro'd my account to send thanks for the EGS version provided by @LennardF1989 
Ran program to set to Width: 2580, Height: 1080 Scale 1.0
Selected Game Launcher: 2560x1440
My 2560*1080 monitor could run the game with a proper aspect ratio with the settings above, somehow

**Comment by Trokinos** [comment]
> 
> 
> [NiohResolution-Steam+EGS.zip](https://github.com/LennardF1989/NiohResolution/files/7148521/NiohResolution-Steam%2BEGS.zip)
> Here you go.

Hello, thank you for this test version, i quickly tried on my "NotSoGood" :) PC and it worked really great for me.
For a performance test i lowered the scale low enough to make the game look like an old PSX one and performance was incredibly smooth with high framerates despite "NotSoGood" PC.  


result :
01a

The UI seems to also be correctly scaled , maybe because i entered a 16/9 resolution ( 1280x720 )  so it's smooth sail so far.

Thank you a lot, i'll be able to increase the scaling as things work incredibly smoothly even at 0.5

**Comment by jrusz** [comment]
Hi, I've tried this fix and I feel like it worked fine with me. I don't have any experience with developing on Windows but I built something with VS code and it worked exactly like described in this comment https://github.com/LennardF1989/NiohResolution/pull/16#issuecomment-917334273 

I have a 3440x1440 monitor and this is how it looks for me 
Nioh Screenshot 2021 09 12 - 10 48 16 22

**Comment by Azrafael** [comment]
With my current resolution of 2560*1080
Using the EGS version shared by @LennardF1989 
Following the steps and selecting 2048*1152 seems to be running well with no noticeable aspect ratio abnormalities.

**Comment by Krzychowy** [comment]
Just tested at 3840x1600, and setting 1920x1080 in launcher does cause the aspect ratio to expand but the picture remains pillarboxed 16:9, so the resulting 21:9 imagine is schrinked inside 16:9 space. Using 3840x2160 in launcher instead seems to be working, the game expands properly and UI is not stretched, there is also no performance difference vs 1920x1080 setting, so both are running at an actual 3840x1600 resolution. The only difference vs older version is that MSI Afterburner OSD is stretched, which was not the case with older versions.

**Comment by Atresia** [comment]
I tried it with a resolution of 2560x1440 and it doesn't work. Am I doing something wrong? Playing the EGS version.
Here are my settings:
image
image

**Comment by LennardF1989** [comment]
Alright, thanks for all the reports. I think the conclusion is that the 1920x1080 mode (in launcher) works for most people, but other resolutions might be better of selecting 4k from the launcher after patching. Can't really put my finger on it, but it's clear that the developers tried to fix something (as one of the magic patches - which are in reality not so magic), is no longer required.

I will release this version as a pre-release and update the messaging to let people know that if they get pillarboxing, they should try to select the 4k resolution (even if their monitor isn't 4K). I will close this issue and start a new one for feedback!

**Pull request closed without merging**
